version: '3'

services:
  app:
    image: webdevops/php-nginx:7.4
    container_name: api-app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    build:
      context: ./
    ports:
      - 8080:80
    volumes:
      - ./:/app:rw
    environment:
      WEB_DOCUMENT_ROOT: /app/public